pc1[0]="A/00:00:00:00:00:01"
pc1[image]="kathara-pytorch"

pc2[0]="A/00:00:00:00:00:02"
pc2[image]="kathara-pytorch"

wireshark[port]="3000:3000"
wireshark[image]="lscr.io/linuxserver/wireshark"
wireshark[bridged]="True"
wireshark[num_terms]="0"
wireshark[ipv6]="False"